@startuml Utilities-Sequence-Pseudo

!define POSITIVERESPONSE 90EE90
!define NEGATIVEERESPONSE EFBBBB
!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE
    LifeLineBackgroundColor #E7E8D1
    LifeLineBorderColor #2C5F2D
    ActorBackgroundColor #FC766AFF
    ActorBorderColor #FC766AFF
    ArrowColor #B85042
    ArrowFontColor #234E70
}

title   **Utilities - showCurrentDate()**
autonumber 1
hide footbox
Caller -> currentDate: Invoke **showCurrentDate()**
activate Caller
activate currentDate
alt TRY
currentDate -> currentDate: Initialize a new DateTime using **DateTime.now()** and assign it to a variable
currentDate -> currentDate: Initialize a DateFormat using **DateFormat()** and assign it to a variable
currentDate -> currentDate: Format the DateTime variable using **format()** method
currentDate --> Caller: Return **current date**
deactivate Caller
deactivate currentDate

==PseudoCode==
hnote across

GET the current date using the **DateTime.now()** and assign it to a variable named **now** of type DateTime

USING the **DateFormat()** to format the date as **dd-MM-yyyy** and assign it a variable named **formatter** of type DateFormat

FORMAT the DateTime varibale named **now** using the **format()** method and assign it a variable name **formated date** of type String

RETURN the **current date**
end note
@enduml