@startuml CreatePostScreen - Class

title **CreatePostScreen - Class**

package Pages{
    package CreatePostScreen{
        class CreatePostScreenModel{
            + NoteService : INoteService
        }
        class CreatePostScreenVM{
            + createNewPost() : Future<void>
            + navigateBackToLandingScreen() : void
            + navigateToResponseScreen() : void
            + onChangetitle(title: String) : void
            + onChangeDescription(description: String): void
        }
        class CreatePostScreen{
            - _createPostScreenVM : CreatePostScreenVM
            + initState() : void
            + dispose() : void
        }
    }
}

package Services{
    package NoteServices{
        interface INoteService{
            + createPost(Post: NoteBO): Future<ServiceResult<bool>>
        }
    }
}

package BOs{
    package NoteBO{
        class NoteBO{
        }
    }
}

CreatePostScreenVM --> NoteBO 
CreatePostScreenVM --> INoteService 
CreatePostScreenVM --> CreatePostScreenModel : extends
CreatePostScreen --> CreatePostScreenVM : uses
@enduml