@startuml CreatePostScreen-Sequence-Pseudo

!define POSITIVERESPONSE 90EE90
!define NEGATIVEERESPONSE EFBBBB
!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE
    LifeLineBackgroundColor #E7E8D1
    LifeLineBorderColor #2C5F2D
    ActorBackgroundColor #FC766AFF
    ActorBorderColor #FC766AFF
    ArrowColor #B85042
    ArrowFontColor #234E70
}

title   **CreatePostScreen - initState()**
actor User
autonumber 1
hide footbox
User -> CreatePostScreen: Invoke **initState()**
activate User
activate CreatePostScreen
alt (TRY)
    CreatePostScreen -> CreatePostScreen: Add a listener to the navigationStream and listen to the events

    alt #POSITIVERESPONSE IF (event is NavigatorPush)
        CreatePostScreen-> CreatePostScreen: Push the context to the **Response**\n**Screen** and data as **statuscode**.
        CreatePostScreen --> User: Returns
    else #POSITIVERESPONSE IF (event is NavigatorPop) 
        CreatePostScreen-> CreatePostScreen: Pop the context to the **Landing Screen**.
        CreatePostScreen --> User: Returns
    end

    CreatePostScreen -> CreatePostScreen: Add a listener to the textfieldcontroller.Stream and listen to the events

    alt #POSITIVERESPONSE IF (event is TitleText)
        CreatePostScreen-> CreatePostScreen: Assign the event data to the text editing controller.
        CreatePostScreen --> User: Returns
    end

    CreatePostScreen -> CreatePostScreen: Add a listener to the textfieldcontroller.Stream and listen to the events

    alt #POSITIVERESPONSE IF (event is DescriptionText)
        CreatePostScreen-> CreatePostScreen: Assign the event data to the text editing controller.
        CreatePostScreen --> User: Returns
    end

else #NEGATIVEERESPONSE (CATCH)
    CreatePostScreen -> CreatePostScreen : Write exception logs
    CreatePostScreen --> User: Returns
    deactivate CreatePostScreen
    deactivate User
end

==Pseudocode==
hnote across
**TRY**
    
        Add a listener to the **navigationStream** and listen to the **events**
        
        **IF event is NavigatorPush**

                Push the context to the **ResponseScreen** with data as **status code**
        
        **IF event is NavigatorPop**

                Pop the context to the **LandingScreen Screen**
        
        Add a listener to the **textfieldcontroller** and listen to the **events**
    
        **IF event is TitleText**

                Assign the event data to the controller
        
        Add a listener to the **textfieldcontroller** and listen to the **events**
    
        **IF event is DescriptionText**

                Assign the event data to the controller

**CATCH**

    INVOKE **writeException()** on the exception object **ex**.

end note

newpage  **CreatePostScreen - dispose()**
!define POSITIVERESPONSE 90EE90
!define NEGATIVEERESPONSE EFBBBB
!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE
    LifeLineBackgroundColor #E7E8D1
    LifeLineBorderColor #2C5F2D
    ActorBackgroundColor #FC766AFF
    ActorBorderColor #FC766AFF
    ArrowColor #B85042
    ArrowFontColor #234E70
}

autonumber 1
hide footbox
User -> CreatePostScreen: Invoke **dispose()**
activate User
activate CreatePostScreen
CreatePostScreen -> CreatePostScreen: Dispose the **navigationStream**
CreatePostScreen -> CreatePostScreen: Dispose the **texteditingcontroller** for **title**.
CreatePostScreen -> CreatePostScreen: Dispose the **texteditingcontroller** for **description**.
CreatePostScreen --> User: Returns
deactivate CreatePostScreen
deactivate User

==Pseudocode==
hnote across

USING **dispose()** method dispose the **navigationStream**

USING **dispose()** method dispose the **texteditingcontroller** for the **title**

USING **dispose()** method dispose the **texteditingcontroller** for the **description** 

end note

newpage Create Post
autonumber
hide footbox
User -> CreatePostScreen: **Create** Button.Clicked
activate User
activate CreatePostScreen
CreatePostScreen -> CreatePostScreenVM: Invoke **navigateToResponseScreen()**
activate CreatePostScreenVM
CreatePostScreenVM --> CreatePostScreen: Returns
deactivate CreatePostScreenVM
CreatePostScreen -> User: Display **ResponseScreen**
deactivate CreatePostScreen
deactivate User
==Pseudocode==
hnote across

INVOKE **navigateToResponseScreen()** method

DISPLAY **ResponseScreen** to the User 

end note
newpage goBack Post
autonumber
hide footbox
User -> CreatePostScreen: **goBack** Button.Clicked
activate User
activate CreatePostScreen
CreatePostScreen -> CreatePostScreenVM: Invoke **navigateBackToLandingScreen()**
activate CreatePostScreenVM
CreatePostScreenVM --> CreatePostScreen: Returns
deactivate CreatePostScreenVM
CreatePostScreen -> User: Display **LandingScreen**
deactivate CreatePostScreen
deactivate User
==Pseudocode==
hnote across

INVOKE **navigateBackToLandingScreen()** method

DISPLAY **LandingScreen** to the User 

end note
@enduml