@startuml CreatePostScreenVM-Sequence-Pseudo

!define POSITIVERESPONSE 90EE90
!define NEGATIVEERESPONSE EFBBBB
!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE
    LifeLineBackgroundColor #E7E8D1
    LifeLineBorderColor #2C5F2D
    ActorBackgroundColor #FC766AFF
    ActorBorderColor #FC766AFF
    ArrowColor #B85042
    ArrowFontColor #234E70
}

title   **CreatePostScreenVM - createNewPost()**
autonumber 1
hide footbox
Caller -> CreatePostScreenVM: Invoke **createNewPost()**
activate Caller
activate CreatePostScreenVM
alt (TRY)
    CreatePostScreenVM -> CreatePostScreenVM: Create an instance newPost for createPost (Post: PostBO)\nand assign it to a variable
    CreatePostScreenVM -> CreatePostScreenVM: Set **@isLoading** is true
    CreatePostScreenVM -> Services: Assign the variable to the service as a parameter
    activate Services
    Services --> CreatePostScreenVM : Returns  **ServiceResult<bool>**
    deactivate Services
    alt #POSITIVERESPONSE (if status code is OK)
        CreatePostScreenVM -> CreatePostScreenVM : Set the **data** as **statusCode** to the **navigationStream**.  
        CreatePostScreenVM --> Caller : Returns
    else #NEGATIVEERESPONSE (if status code is Bad Request)
        CreatePostScreenVM -> CreatePostScreenVM : Assign the **statusCode** as the **data** to the **navigationStream**.
        CreatePostScreenVM --> Caller : Returns
    end
else #NEGATIVEERESPONSE (CATCH)
    CreatePostScreenVM -> CreatePostScreenVM : Write exception logs
    CreatePostScreenVM --> Caller: Returns
    deactivate CreatePostScreenVM
    deactivate Caller
end

==Pseudocode==
hnote across
**TRY**

    CREATE an instance newPost for createPost (Post: PostBO) and assign it to a variable

    SET **@isLoading** is true

    INVOKE **createPost(Post: PostBO)** method

    Returns the  **ServiceResult<bool>**

**IF the the status code in serviceResult is OK**

    ASSIGN the **message** as the **data** to the **navigationStream**.

    ASSIGN the **List<PostBO>** to the variable **originalListOfPosts** and **@tempListOfPosts**

**IF status code in ServiceResult is Netwrok Failure**

    ASSIGN the **message** as the **data** to the **navigationStream**.

**CATCH**

    INVOKE **writeException()** on the exception object ex.

end note


newpage **CreatePostScreenVM - navigateToResponseScreen(Status Code: statusCode)**
!define POSITIVERESPONSE 90EE90
!define NEGATIVEERESPONSE EFBBBB
!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE
    LifeLineBackgroundColor #E7E8D1
    LifeLineBorderColor #2C5F2D
    ActorBackgroundColor #FC766AFF
    ActorBorderColor #FC766AFF
    ArrowColor #B85042
    ArrowFontColor #234E70
}

autonumber 1
hide footbox
Caller -> CreatePostScreenVM: Invoke **navigateToResponseScreen()**
activate Caller
activate CreatePostScreenVM
alt #POSITIVERESPONSE (TRY)
CreatePostScreenVM -> CreatePostScreenVM : add the **NavigatorPush()** method to the navigation stream\nand assign **statusCode** to the **data** parameter 
CreatePostScreenVM -> Caller: Returns
else #NEGATIVEERESPONSE (CATCH)
    CreatePostScreenVM -> CreatePostScreenVM : Write exception logs
    CreatePostScreenVM --> Caller: Returns
    deactivate CreatePostScreenVM
    deactivate Caller
end

deactivate Caller
deactivate CreatePostScreenVM
==Pseudocode==
hnote across
**TRY**

    ADD the **NavigatorPush()** method which has pageconfig of **ResponseScreen** and data as **status code** to the navgation stream

**CATCH**

    INVOKE **writeException()** on the exception object ex.
end note

newpage **CreatePostScreenVM - navigateToLandingScreen()**

!define POSITIVERESPONSE 90EE90
!define NEGATIVEERESPONSE EFBBBB
!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE
    LifeLineBackgroundColor #E7E8D1
    LifeLineBorderColor #2C5F2D
    ActorBackgroundColor #FC766AFF
    ActorBorderColor #FC766AFF
    ArrowColor #B85042
    ArrowFontColor #234E70
}
autonumber 1
hide footbox
Caller -> CreatePostScreenVM: Invoke **navigateToLandingScreen()**
activate Caller
activate CreatePostScreenVM
alt #POSITIVERESPONSE (TRY)
CreatePostScreenVM -> CreatePostScreenVM : add the **NavigatorPop()** method to the navigation stream
CreatePostScreenVM -> Caller: Returns
else #NEGATIVEERESPONSE (CATCH)
    CreatePostScreenVM -> CreatePostScreenVM : Write exception logs
    CreatePostScreenVM --> Caller: Returns
    deactivate CreatePostScreenVM
    deactivate Caller
end
==Pseudocode==
hnote across
**TRY**

    ADD the **NavigatorPop()** method

**CATCH**

    INVOKE **writeException()** on the exception object ex.
end note

newpage **CreatePostScreenVM - onTitleChange(title: String)**
!define POSITIVERESPONSE 90EE90
!define NEGATIVEERESPONSE EFBBBB
!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE
    LifeLineBackgroundColor #E7E8D1
    LifeLineBorderColor #2C5F2D
    ActorBackgroundColor #FC766AFF
    ActorBorderColor #FC766AFF
    ArrowColor #B85042
    ArrowFontColor #234E70
}

autonumber 1
hide footbox
Caller -> CreatePostScreenVM: Invoke **onTitleChange(String: title)**
activate Caller
activate CreatePostScreenVM
alt #POSITIVERESPONSE (TRY)    
    CreatePostScreenVM -> CreatePostScreenVM: add the textfield data to the text field controller.
    CreatePostScreenVM --> Caller: Returns
else #NEGATIVEERESPONSE (CATCH)
    CreatePostScreenVM -> CreatePostScreenVM : Write exception logs
    CreatePostScreenVM --> Caller: Returns
    deactivate CreatePostScreenVM
    deactivate Caller
end
==Pseudocode==
hnote across
**TRY**

    Add the textfield data to the text field contorller

**CATCH**

    INVOKE **writeException()** on the exception object ex.
end note

newpage **CreatePostScreenVM - onDescriptionChange(description: String)**
!define POSITIVERESPONSE 90EE90
!define NEGATIVEERESPONSE EFBBBB
!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE
    LifeLineBackgroundColor #E7E8D1
    LifeLineBorderColor #2C5F2D
    ActorBackgroundColor #FC766AFF
    ActorBorderColor #FC766AFF
    ArrowColor #B85042
    ArrowFontColor #234E70
}
autonumber 1
hide footbox
Caller -> CreatePostScreenVM: Invoke **onDescriptionChange(description: String)**
activate Caller
activate CreatePostScreenVM
alt #POSITIVERESPONSE (TRY)
    CreatePostScreenVM -> CreatePostScreenVM: add the textfield data to the text field controller.
    CreatePostScreenVM --> Caller: Returns
else #NEGATIVEERESPONSE (CATCH)
    CreatePostScreenVM -> CreatePostScreenVM : Write exception logs
    CreatePostScreenVM --> Caller: Returns
    deactivate CreatePostScreenVM
    deactivate Caller
end

==Pseudocode==
hnote across
**TRY**

    Add the textfield data to the text field contorller

**CATCH**

    INVOKE **writeException()** on the exception object ex.
end note
@enduml