@startuml NoteBO-Sequence-Pseudo

!define POSITIVERESPONSE 90EE90
!define NEGATIVEERESPONSE EFBBBB
!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE
    LifeLineBackgroundColor #E7E8D1
    LifeLineBorderColor #2C5F2D
    ActorBackgroundColor #FC766AFF
    ActorBorderColor #FC766AFF
    ArrowColor #B85042
    ArrowFontColor #234E70
}

title   **NoteBOExtension - sortPostsByDate()**
autonumber 1
hide footbox
participant Caller as C
participant NoteBOExtension as NE
C -> NE : Invoke **sortUserDetailsInAsscendingOrderById()**
activate C
activate NE
NE -> NE : Sort the **@tempListOfPosts** using **sort()** and\nuse **CompareTo()** to compare **date**
NE --> C : Returns **List<UserBO>**
deactivate NE
deactivate C

==Pseudocode==
hnote across
 SORT the **@tempListOfPosts** using **sort()** and inside **sort()**,pass the **date** to **compareTo()** to compare.
end note
 @enduml