@startuml LandingScreenVM-Sequence-Pseudo

!define POSITIVERESPONSE 90EE90
!define NEGATIVEERESPONSE EFBBBB
!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE
    LifeLineBackgroundColor #E7E8D1
    LifeLineBorderColor #2C5F2D
    ActorBackgroundColor #FC766AFF
    ActorBorderColor #FC766AFF
    ArrowColor #B85042
    ArrowFontColor #234E70
}

title   **LandingScreenVM - fetchPosts()**
autonumber 1
hide footbox
Caller -> LandingScreenVM: Invoke **fetchPosts()**
activate Caller
activate LandingScreenVM
alt #POSITIVERESPONSE (TRY)
    LandingScreenVM -> LandingScreenVM: Set **@isLoading** is true
    LandingScreenVM -> PostService: Invoke **getPosts()**
    activate PostService
    PostService --> LandingScreenVM : Return  **ServiceResult<List<PostBO>>**
    deactivate PostService
    alt #POSITIVERESPONSE (if status code is OK)
        LandingScreenVM -> LandingScreenVM : Set **@isError** to false
        LandingScreenVM -> LandingScreenVM : Assign **List<PostBO>** to **@originalListOfPosts** and **@tempListOfPosts**
        LandingScreenVM --> Caller : Returns
    else #NEGATIVEERESPONSE (if status code is Bad Request)
        LandingScreenVM -> LandingScreenVM : Set serviceResult message in **@errorMessage**
        LandingScreenVM -> LandingScreenVM : Set **@isError** to true
        LandingScreenVM --> Caller : Returns
    end
LandingScreenVM -> LandingScreenVM: Set **@isLoading** is false
LandingScreenVM --> Caller: Returns
else #NEGATIVEERESPONSE (CATCH)
    LandingScreenVM -> LandingScreenVM : write Exception Logs
    LandingScreenVM --> Caller: Returns
    deactivate LandingScreenVM
    deactivate Caller
end

==Pseudocode==
hnote across
**TRY** 

    Set the **@isLoading** is true
    
    INVOKE **getPosts()** method
    
    Returns the  **ServiceResult<List<PostBO>>**

    **IF the the status code is OK**
    
        SET the **@isError** is false
    
        ASSIGN the **List<PostBO>** to the variable **@originalListOfPosts** and **@tempListOfPosts**
    
    **IF status code is Bad Request**
        
        SET the serviceResult message in **@errorMessage**
    
        SET the **@isError** is true
    
**CATCH**
    
    INVOKE **writeException()** on the exception object **ex**.
end note

newpage **LandingScreenVM - sortPosts()**
!define POSITIVERESPONSE 90EE90
!define NEGATIVEERESPONSE EFBBBB
!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE
    LifeLineBackgroundColor #E7E8D1
    LifeLineBorderColor #2C5F2D
    ActorBackgroundColor #FC766AFF
    ActorBorderColor #FC766AFF
    ArrowColor #B85042
    ArrowFontColor #234E70
}

autonumber 1
hide footbox
Caller -> LandingScreenVM: Invoke **sortPosts()**
activate Caller
activate LandingScreenVM
alt #POSITIVERESPONSE (TRY)
    LandingScreenVM -> PostBOExtention: INVOKE **@tempListOfPosts.sortPostsByDate()**
    activate PostBOExtention
    PostBOExtention --> LandingScreenVM : Return sorted **@tempListOfPosts**
    deactivate PostBOExtention
    LandingScreenVM --> Caller: Returns 

else #NEGATIVEERESPONSE (CATCH)
    LandingScreenVM -> LandingScreenVM : writeException logs
    LandingScreenVM --> Caller: Returns
    deactivate LandingScreenVM
    deactivate Caller
end

==Pseudocode==
hnote across
**TRY**

    INVOKE **@tempListOfPosts.sortPostsByDate()** method

    RETURN the sorted **@tempLostOfPosts**

**CATCH**

    INVOKE **writeException()** on the exception object **ex**.
end note

newpage **LandingScreenVM - navigateToCreatePostScreen()**
!define POSITIVERESPONSE 90EE90
!define NEGATIVEERESPONSE EFBBBB
!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE
    LifeLineBackgroundColor #E7E8D1
    LifeLineBorderColor #2C5F2D
    ActorBackgroundColor #FC766AFF
    ActorBorderColor #FC766AFF
    ArrowColor #B85042
    ArrowFontColor #234E70
}
autonumber
hide footbox
Caller -> LandingScreenVM: Invokes **navigateToCreatePostScreen()**
activate Caller
activate LandingScreenVM
alt #POSITIVERESPONSE (TRY)
LandingScreenVM -> LandingScreenVM : add the **NavigatorPush()** method to the navigation stream
LandingScreenVM -> Caller: Returns
else #NEGATIVEERESPONSE (CATCH)
    LandingScreenVM -> LandingScreenVM : write Exception Logs
    LandingScreenVM --> Caller: Returns
    deactivate LandingScreenVM
    deactivate Caller
end

==Pseudocode==
hnote across
**TRY**

    ADD the **NavigatorPush()** method which has pageconfig of **CreatePost screen** and data to the navgation stream

**CATCH**
    
    INVOKE **writeException()** on the exception object **ex**
end note
@enduml