@startuml LandingScreen - Class

title **LandingScreen - Class Diagram**

package Pages{
    package LandingScreen{
        class LandingScreenModel{
            + NoteService : INoteService
            + originalListOfPosts : List<NoteBO>
            + @listOfPosts : List<NoteBO>
            + @isPostLoading : bool
            + @isError : bool
            + @errorMessage: String
        }
        class LandingScreenVM{
            + fetchPosts(): Future<void>
            + sortUsers(): void
            + navigateToCreatePostScreen() : void
        }
        class LandingScreen{
            - _landingScreenVM : LandingScreenVM
            + initState() : void
            + dispose(): void
        }
    }
}

package BOs{
    package NoteBO{
        class NoteBO{
        }
        class NoteBOExtension{
            + sortPostsByDate() : List<NoteBO>
        }
    }
}

package Services{
    package NoteService{
        interface INoteService{
            + getPosts(): Future<ServiceResult<List<NoteBO>>>
        }
    }
}

LandingScreenVM --> LandingScreenModel : Extends
LandingScreen --> LandingScreenVM: Uses
LandingScreenVM --> NoteBO
NoteBOExtension --> NoteBO
LandingScreenVM -> NoteBOExtension
LandingScreenVM -> INoteService
@enduml