@startuml ResponseScreen - Class

title ResponseScreen - Class Diagram

package Pages{
    package ResponseScreen{
        class ResponseScreenModel{
            + @successMessage: String
            + @failureMessage: String
            + @isVisible: bool
        }
        class ResponseScreenVM{
            + Constructor(String: Status Code) : void
            + navigateToLandingScreen() : void
        }
        class ResponseScreen{
            - _responseScreenVM : ResponseScreenVM
            + initState(): void
            + dispose(): void
        }
    }
}

ResponseScreen --> ResponseScreenVM: uses
ResponseScreenVM --> ResponseScreenModel : extends
@enduml