@startuml ResponseScreen - Class

title ResponseScreen - Class Diagram

package Pages{
    package ResponseScreen{
        class ResponseScreenModel{
            + @message: String
            + @statusCode : String
        }
        class ResponseScreenVM{
            + navigateToLandingScreen() : void
        }
        class ResponseScreen{
            - _responseScreenVM : ResponseScreenVM
            + initState(): void
            + dispose(): void
        }
    }
}

ResponseScreen --> ResponseScreenVM : Uses
ResponseScreenVM --> ResponseScreenModel : Extends
@enduml